### ISSUE TITLE
What license is ToSRAM under?

### ISSUE THREAD

**Issue by betaveros** [johnchen902/ToSRAM#1]
Why is there an empty LICENSE file in the root directory?

(I would like to use the screenshot for a presentation and am seeking permission to do so.)

**Comment by johnchen902** [comment]
I've never really studied things about licenses, so I'm not sure which license I'd use now. Wait for... probably an hour or two.

**Comment by johnchen902** [comment]
This project is now licensed under GPL Version 2.
